apiVersion: v1
kind: Namespace
metadata:
  name: test-app
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: disabled
